import Sandwich from "../images/Sandwich.jpg";
import Pancake from "../images/pancake.jpg";
import Pizza from "../images/pizza.jpg";
import Burger from "../images/burger.jpg";
import Momos from "../images/momos.jpg";
import Dosa from "../images/dosa.jpg";
import Pavbhaji from "../images/pavbhaji.jpg";
import Chapati from "../images/chapati.jpg";
import Idli from "../images/idli.jpg";
import Noodle from "../images/noodles.jpg";
import Rice from "../images/rice.jpg";
import Daal from "../images/daal.jpg";
export const MenuList=[
[
   {
        name:"Sandwich",
        image:Sandwich,
        price:100,
        type:"Veg",
   },
   {
    name:"Pancake",
    image:Pancake,
    price:150,
    type:"Veg",
   },
   {
    name:"Pizza",
    image:Pizza,
    price:100,
    type:"Veg",
   },
   {
    name:"Burger",
    image:Burger,
    price:50,
    type:"Veg",
   },
   {
    name:"Momos",
    image:Momos,
    price:80,
    type:"Veg",
   },
   {
    name:"Dosa",
    image:Dosa,
    price:80,
    type:"Veg",
   },
   {
    name:"Pav Bhaji",
    image:Pavbhaji,
    price:120,
    type:"Veg",
   },
   {
    name:"Chapati",
    image:Chapati,
    price:20,
    type:"Veg",
   },
   {
    name:"Noodles",
    image:Noodle,
    price:60,
    type:"Veg",
   },
   {
    name:"Idli",
    image:Idli,
    price:80,
    type:"Veg",
   },
   {
    name:"Rice",
    image:Rice,
    price:40,
    type:"Veg",
},
{
    name:"Daal",
    image:Daal,
    price:50,
    type:"Veg",
},
],
[
    {
     name:"Sandwich",
     image:Sandwich,
     price:100,
     type:"Veg",
    },
    {
     name:"Pancake",
     image:Pancake,
     price:150,
     type:"Veg",
    },
    {
     name:"Pizza",
     image:Pizza,
     price:100,
     type:"Veg",
    },
    {
     name:"Burger",
     image:Burger,
     price:50,
     type:"Veg",
    },
    {
     name:"Momos",
     image:Momos,
     price:80,
     type:"Veg",
    },
 ],
 [
    {
     name:"Dosa",
     image:Dosa,
     price:80,
     type:"Veg",
    },
    {
     name:"Pav Bhaji",
     image:Pavbhaji,
     price:120,
     type:"Veg",
    },
    {
     name:"Noodles",
     image:Noodle,
     price:60,
     type:"Veg",
    },
    {
     name:"Idli",
     image:Idli,
     price:80,
     type:"Veg",
    },
 ],
 [
    {
     name:"Chapati",
     image:Chapati,
     price:20,
     type:"Veg",
    },
    {
        name:"Rice",
        image:Rice,
        price:40,
        type:"Veg",
    },
    {
        name:"Daal",
        image:Daal,
        price:50,
        type:"Veg",
    },
 ],
]